### ISSUE TITLE
Provisioning

### ISSUE THREAD

**Issue by joeblew99** [ubuntu-core/snappy#218]
I need to use the snappy AB transactional provisioning, and snappy OEM.

The use case is for having devices out in the field, behind a dynamic WAN ip. So basically IOT style network topology.

I write lots of go and am stoked you have written all this in golang.

But I am having trouble finding resources that dive into setting up provisioning servers, creating OEM images etc.

The hardware is a mix of arm and x86.

Sorry to ask on github, but there's so little code samples on this on the web. Not yet.

We are based in Berlin BTW.

**Comment by elopio** [comment]
Hello. Welcome to snappy. Please ask your question in http://askubuntu.com/.
