### ISSUE TITLE
go build -o snappy_armhf github.com/ubuntu-core/snappy/cmd/snappy won't work

### ISSUE THREAD

**Issue by aiken** [ubuntu-core/snappy#277]
I ran the command, but can not get it work

root@75aff6a3c7a1:/snapcraft# go build -o snappy_armhf github.com/ubuntu-core/snappy/cmd/snappycan't load package: package github.com/ubuntu-core/snappy/cmd/snappy: cannot find package "github.com/ubuntu-core/snappy/cmd/snappy" in any of:
	/usr/lib/go/src/pkg/github.com/ubuntu-core/snappy/cmd/snappy (from $GOROOT)
	/root/go/src/github.com/ubuntu-core/snappy/cmd/snappy (from $GOPATH)

**Comment by niemeyer** [comment]
It doesn't look like you have the snappy source code at hand?  It also doesn't look like a good idea to run these commnads as root, by the way.

**Comment by sergiusens** [comment]
Just want to point out the odd `snapcraft` in the expanded `PS1`, maybe confusing projects here?
