### ISSUE TITLE
not getting an ipv4 address on the first boot

### ISSUE THREAD

**Issue by chipaca** [ubuntu-core/snappy#30]
Testing the beaglebone and trying to reproduce a problem Paul is having on the lab we found that on the first boot, the board doesn't get an ipv4 address assigned.

Tested in beaglebone black revC, rolling edge #191.

(BeagleBoneBlack)ubuntu@localhost:~$ ifconfig
eth0 Link encap:Ethernet HWaddr 84:eb:18:93:41:5a
          inet6 addr: fdad:31e6:e786:0:86eb:18ff:fe93:415a/64 Scope:Global
          inet6 addr: fe80::86eb:18ff:fe93:415a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
          RX packets:75 errors:0 dropped:0 overruns:0 frame:0
          TX packets:69 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:12598 (12.5 KB) TX bytes:11778 (11.7 KB)
          Interrupt:169

lo Link encap:Local Loopback
          inet addr:127.0.0.1 Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING MTU:65536 Metric:1
          RX packets:400 errors:0 dropped:0 overruns:0 frame:0
          TX packets:400 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:32000 (32.0 KB) TX bytes:32000 (32.0 KB)

After a reboot, the v4 address is there:

eth0 Link encap:Ethernet HWaddr 84:eb:18:93:41:5a
          inet addr:192.168.2.196 Bcast:192.168.2.255 Mask:255.255.255.0
          inet6 addr: fdad:31e6:e786:0:86eb:18ff:fe93:415a/64 Scope:Global
          inet6 addr: fe80::86eb:18ff:fe93:415a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST MTU:1500 Metric:1
          RX packets:76 errors:0 dropped:0 overruns:0 frame:0
          TX packets:74 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11071 (11.0 KB) TX bytes:10796 (10.7 KB)
          Interrupt:169

lo Link encap:Local Loopback
          inet addr:127.0.0.1 Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING MTU:65536 Metric:1
          RX packets:160 errors:0 dropped:0 overruns:0 frame:0
          TX packets:160 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:12800 (12.8 KB) TX bytes:12800 (12.8 KB)

**Comment by chipaca** [comment]
From https://bugs.launchpad.net/snappy/+bug/1503329

**Comment by chipaca** [comment]
@fgimenez, @elopio, this is fixed, right?

**Comment by elopio** [comment]
It is. Thanks you.
