### ISSUE TITLE
Daemons and routes should not use global state

### ISSUE THREAD

**Issue by niemeyer** [ubuntu-core/snappy#34]
Reasonable context in PR #33.

**Comment by chipaca** [comment]
Notice gorilla.mux itself uses global state.

**Comment by niemeyer** [comment]
Depending on how it is doing that, we should look for alternatives, or just stick to net/http which os what I usually do.

**Comment by niemeyer** [comment]
Moved to https://bugs.launchpad.net/snappy/+bug/1534148.
