### ISSUE TITLE
[all-snap] only set snappy_{os,kernel} to snappy_good_{os,kernel} if the later is non-empty

### ISSUE THREAD

**Issue by mvo5** [ubuntu-core/snappy#5]
Right now snappy_{os,kernel} will be set on trial_boot=1 to snappy_good_{os,kernel}. However on first boot when snappy_good_{os,kernel} is empty (and trial_boot is set to 1 by grub) there is a race that if someone reboots before book-ok is run the snappy_{os,kernel} is unset. So the grub/uboot cfg needs to check if snappy_good_{os,kernel} is empty or not.

**Comment by niemeyer** [comment]
Moved to https://bugs.launchpad.net/snappy/+bug/1534137.
