### ISSUE TITLE
BootAssetFiles have new "Dst" key that we should support

### ISSUE THREAD

**Issue by mvo5** [ubuntu-core/snappy#7]
In order to support boot asset files that are outside of the /boot/{grub,uboot}/ directory we added a new "dst" to the bootassts yaml that is relative to the boot partition instead of relative to the bootloader directory (which is what we are currently using). That is needed to support putting the fwupdate.efi file into /boot/efi/EFI/ubuntu/. Ubuntu-device-flash got this support via https://code.launchpad.net/~mvo/goget-ubuntu-touch/boot-assets-dst/+merge/275757 already. We need to add this support for "dst" to snappy itself too.

**Comment by mvo5** [comment]
As suggest on irc by gustavo: "target-absolute" is a better name.

**Comment by niemeyer** [comment]
Moved to https://bugs.launchpad.net/snappy/+bug/1534154.
