### ISSUE TITLE
Differences between a/b snappy and "all-snap"?

### ISSUE THREAD

**Issue by MichaelTunnell** [ubuntu-core/snappy#751]
> Note that this document describes systems that use a snappy a/b partition layout. Newer snappy systems use a different mechanism called "all-snap" that is using a different strategy for the transnational updates.

I am trying to learn as much as possible on Snappy but I can't seem to find an explanation for all-snap.

**Comment by zyga** [comment]
A/B snappy used two partitions. All-snaps uses one partition and has every part of the system delivered as an immutable squashfs file.

**Comment by MichaelTunnell** [comment]
Thank you for that answer. Last question about that, so the A/B method is still being used now just in one partition instead of two? I mean, the rollback feature is still possible with the all-snap version right?

**Comment by elopio** [comment]
That's right.

Thanks for your interest. Next time please ask your question in http://askubuntu.com/ or in one of the mailing lists.
