### ISSUE TITLE
Add more examples to docs/frameworks.md

### ISSUE THREAD

**Issue by dholbach** [ubuntu-core/snappy#80]
It became clear in the [frameworks session at UOS](http://summit.ubuntu.com/uos-1511/meeting/22596/core-1511-new-snappy-frameworks/) that many struggle with the concept of frameworks and that it's hard to figure what makes a suitable framework and what should likely be bundled elsewhere.

If we could describe some of the available frameworks, why they are a framework, how they work and what for example isn't a framework, this would be a lot clearer.

**Comment by niemeyer** [comment]
We're trying to kill the concept of frameworks, so I'll close this for the time being.
